<?php
/*
HTMLFilter 1.0 - HTML/XHTML filter
----------------------------------
against XSS(Cross Site Scripting) & CSRF(Cross-site request forgery)
Copyright (C) 2008-2009  Jacob Lee

This program is free software and open source software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 2 of the License,
or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
59 Temple Place, Suite 330, Boston, MA  02111-1307  USA  or visit
http://www.gnu.org/licenses/gpl.html

*** AUTHOR INFORMATION ***

E-mail:      letsgolee at lycos dot co dot kr
*/

/*
HTMLFilter Configuration File

Short Manual:
-------------

$block_url_syntax
	* type: array
	* contains URL syntaxes that you want to prohibit.

$tags
	* type: array
	* contains all the information about HTML tags or nodeName
	* set false not to be used or banned.

$tag_attributes
	* type: array
	* contains all the information about attributes.
*/
class HTMLFilterConfig
{
	var $block_url_syntax = array
	(
		/* '/hacker\.com/i' */
		/* '/'.preg_quote(gethostbyname('hacker.com')).'/' */
		/* '/'.preg_quote($base_url).'\/adm\/[a-z]+\.php/i' */
	);

	var $css_syntax = '/^([a-z0-9#\!\.\,\-\*°¡-ÆR\t ]+)$/i';

	// attributes that need URL filtering
	// <img style="background-image:url('http://hackers.site.net')" />
	var $attributes_need_url_filtering = array(
		'background-image',
		'background',
		'-moz-binding',
		'behavior',
		'list-style-image'
	);

	// <a href="javascript:alert('XSS')">
	var $script_types = array(
		'javascript:',
		'behavior:',
		'vbscript:',
		'mocha:',
		'livescript:'
	);

	// object tag security issues
	var $object_security = array(
		// 'name'=>'default value'
		'invokeurls'=>'false',
		'autostart'=>'false',
		'allowscriptaccess'=>'never',
		'allownetworking'=>'internal',
		'enablecontextmenu'=>'false'
	);

	var $tags = array
	(
		'!doctype' => false,
		'a' => true,
		'abbr' => true,
		'acronym' => true,
		'address' => true,
		'applet' => true,
		'area' => true,
		'b' => true,
		'base' => true,
		'basefont' => true,
		'bdo' => true,
		'bgsound' => true,
		'big' => true,
		'blink' => true,
		'blockquote' => true,
		'body' => false,
		'br' => true,
		'button' => false,
		'caption' => true,
		'center' => true,
		'cite' => true,
		'code' => true,
		'col' => true,
		'colgroup' => true,
		'comment' => false,
		'dd' => true,
		'del' => true,
		'dfn' => true,
		'dir' => true,
		'div' => true,
		'dl' => true,
		'dt' => true,
		'em' => true,
		'embed' => true,
		'fieldset' => true,
		'font' => true,
		'form' => false,
		'frame' => false,
		'frameset' => false,
		'h1' => true,
		'h2' => true,
		'h3' => true,
		'h4' => true,
		'h5' => true,
		'h6' => true,
		'head' => false,
		'hr' => true,
		'html' => false,
		'i' => true,
		'iframe' => false,
		'img' => true,
		'input' => false,
		'ins' => true,
		'isindex' => true,
		'kbd' => true,
		'label' => true,
		'legend' => true,
		'li' => true,
		'listing' => false,
		'link' => false,
		'map' => true,
		'marquee' => true,
		'menu' => false,
		'meta' => false,
		'multicol' => true,
		'nobr' => true,
		'noframes' => false,
		'noscript' => false,
		'object' => true,
		'ol' => true,
		'optgroup' => true,
		'option' => false,
		'p' => true,
		'param' => true,
		'plaintext' => true,
		'pre' => true,
		'q' => true,
		's' => true,
		'samp' => true,
		'script' => false,
		'select' => false,
		'server' => true,
		'small' => true,
		'sound'=> true,
		'spacer' => false,
		'span' => true,
		'strike' => true,
		'strong' => true,
		'style' => false,
		'sub' => true,
		'sup' => true,
		'table' => true,
		'tbody' => true,
		'td' => true,
		'textarea' => false,
		'textflow' => true,
		'tfoot' => true,
		'th' => true,
		'thead' => true,
		'title' => false,
		'tr' => true,
		'tt' => true,
		'u' => true,
		'ul' => true,
		'var' => true,
		'wbr' => true,
		'xmp' => true
	);

	var $tag_attributes = array
	(
		'!doctype' => array
		(

		),
		'a' => array
		(
			'accesskey' => true,
			'charset' => true,
			'class' => true,
			'coords' => true,
			'dir' => true,
			'href' => true,
			'hreflang' => true,
			'id' => true,
			'lang' => true,
			'name' => true,
			'onblur' => false,
			'onclick' => false,
			'ondblclick' => false,
			'onfocus' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'rel' => true,
			'rev' => true,
			'shape' => true,
			'style' => true,
			'tabindex' => true,
			'target' => true,
			'title' => true,
			'type' => true
		),
		'abbr' => array
		(
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'acronym' => array
		(
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'address' => array
		(
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'applet' => array
		(
			'align' => true,
			'alt' => true,
			'archive' => true,
			'class' => true,
			'code' => true,
			'codebase' => true,
			'height' => true,
			'hspace' => true,
			'id' => true,
			'name' => true,
			'object' => true,
			'style' => true,
			'title' => true,
			'vspace' => true,
			'width' => true
		),
		'area' => array
		(
			'accesskey' => true,
			'alt' => true,
			'class' => true,
			'coords' => true,
			'dir' => true,
			'href' => true,
			'id' => true,
			'lang' => true,
			'nohref' => true,
			'onblur' => false,
			'onclick' => false,
			'ondblclick' => false,
			'onfocus' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'shape' => true,
			'style' => true,
			'tabindex' => true,
			'target' => true,
			'title' => true
		),
		'b' => array
		(
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'base' => array
		(
			'href' => true,
			'target' => true
		),
		'basefont' => array
		(
			'color' => true,
			'face' => true,
			'id' => true,
			'size' => true
		),
		'bdo' => array
		(
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'style' => true,
			'title' => true
		),
		'big' => array
		(
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'blockquote' => array
		(
			'cite' => true,
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'body' => array
		(
			'alink' => true,
			'background' => true,
			'bgcolor' => true,
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'link' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onload' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'onunload' => false,
			'style' => true,
			'text' => true,
			'title' => true,
			'vlink' => true
		),
		'br' => array
		(
			'class' => true,
			'clear' => true,
			'id' => true,
			'style' => true,
			'title' => true
		),
		'button' => array
		(
			'accesskey' => true,
			'class' => true,
			'dir' => true,
			'disabled' => true,
			'id' => true,
			'lang' => true,
			'name' => true,
			'onblur' => false,
			'onclick' => false,
			'ondblclick' => false,
			'onfocus' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'tabindex' => true,
			'title' => true,
			'type' => true,
			'value' => true
		),
		'caption' => array
		(
			'align' => true,
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'center' => array
		(
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'cite' => array
		(
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'code' => array
		(
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'col' => array
		(
			'align' => true,
			'char' => true,
			'charoff' => true,
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'span' => true,
			'style' => true,
			'title' => true,
			'valign' => true,
			'width' => true
		),
		'colgroup' => array
		(
			'align' => true,
			'char' => true,
			'charoff' => true,
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'span' => true,
			'style' => true,
			'title' => true,
			'valign' => true,
			'width' => true
		),
		'dd' => array
		(
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'del' => array
		(
			'cite' => true,
			'class' => true,
			'datetime' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'dfn' => array
		(
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'dir' => array
		(
			'class' => true,
			'compact' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'div' => array
		(
			'align' => true,
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'dl' => array
		(
			'class' => true,
			'compact' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'dt' => array
		(
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'em' => array
		(
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'embed' => array
		(
			'height' => true,
			'pluginspage' => true,
			'quality' => true,
			'src' => true,
			'type' => true,
			'width' => true,
			'allowscriptaccess' => false
		),
		'fieldset' => array
		(
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'font' => array
		(
			'class' => true,
			'color' => true,
			'dir' => true,
			'face' => true,
			'id' => true,
			'lang' => true,
			'size' => true,
			'style' => true,
			'title' => true
		),
		'form' => array
		(
			'accept' => true,
			'accept-charset' => true,
			'action' => true,
			'class' => true,
			'dir' => true,
			'enctype' => true,
			'id' => true,
			'lang' => true,
			'method' => true,
			'name' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'onreset' => false,
			'onsubmit' => false,
			'style' => true,
			'target' => true,
			'title' => true
		),
		'frame' => array
		(
			'class' => true,
			'frameborder' => true,
			'id' => true,
			'longdesc' => true,
			'marginheight' => true,
			'marginwidth' => true,
			'name' => true,
			'noresize' => true,
			'scrolling' => true,
			'src' => true,
			'style' => true,
			'title' => true
		),
		'frameset' => array
		(
			'class' => true,
			'cols' => true,
			'id' => true,
			'onload' => false,
			'onunload' => false,
			'rows' => true,
			'style' => true,
			'title' => true
		),
		'h1' => array
		(
			'align' => true,
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'h2' => array
		(
			'align' => true,
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'h3' => array
		(
			'align' => true,
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'h4' => array
		(
			'align' => true,
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'h5' => array
		(
			'align' => true,
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'h6' => array
		(
			'align' => true,
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'head' => array
		(
			'dir' => true,
			'lang' => true,
			'profile' => true
		),
		'hr' => array
		(
			'align' => true,
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'noshade' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'size' => true,
			'style' => true,
			'title' => true,
			'width' => true
		),
		'html' => array
		(
			'dir' => true,
			'lang' => true,
			'version' => true
		),
		'i' => array
		(
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'iframe' => array
		(
			'align' => true,
			'class' => true,
			'frameborder' => true,
			'height' => true,
			'id' => true,
			'longdesc' => true,
			'marginheight' => true,
			'marginwidth' => true,
			'name' => true,
			'scrolling' => true,
			'src' => true,
			'style' => true,
			'title' => true,
			'width' => true
		),
		'img' => array
		(
			'align' => true,
			'alt' => true,
			'border' => true,
			'class' => true,
			'dir' => true,
			'dynsrc' => true,
			'height' => true,
			'hspace' => true,
			'id' => true,
			'ismap' => true,
			'lang' => true,
			'longdesc' => true,
			'lowsrc' => true,
			'name' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'src' => true,
			'style' => true,
			'title' => true,
			'usemap' => true,
			'vspace' => true,
			'width' => true
		),
		'input' => array
		(
			'accept' => true,
			'accesskey' => true,
			'align' => true,
			'alt' => true,
			'checked' => true,
			'class' => true,
			'dir' => true,
			'disabled' => true,
			'id' => true,
			'ismap' => true,
			'lang' => true,
			'maxlength' => true,
			'name' => true,
			'onblur' => false,
			'onchange' => false,
			'onclick' => false,
			'ondblclick' => false,
			'onfocus' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'onselect' => false,
			'readonly' => true,
			'size' => true,
			'src' => true,
			'style' => true,
			'tabindex' => true,
			'title' => true,
			'type' => true,
			'usemap' => true,
			'value' => true
		),
		'ins' => array
		(
			'cite' => true,
			'class' => true,
			'datetime' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'isindex' => array
		(
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'prompt' => true,
			'style' => true,
			'title' => true
		),
		'kbd' => array
		(
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'label' => array
		(
			'accesskey' => true,
			'class' => true,
			'dir' => true,
			'for' => true,
			'id' => true,
			'lang' => true,
			'onblur' => false,
			'onclick' => false,
			'ondblclick' => false,
			'onfocus' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'legend' => array
		(
			'accesskey' => true,
			'align' => true,
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'li' => array
		(
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true,
			'type' => true,
			'value' => true
		),
		'link' => array
		(
			'charset' => true,
			'class' => true,
			'dir' => true,
			'href' => true,
			'hreflang' => true,
			'id' => true,
			'lang' => true,
			'media' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'rel' => true,
			'rev' => true,
			'style' => true,
			'target' => true,
			'title' => true,
			'type' => true
		),
		'map' => array
		(
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'name' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'menu' => array
		(
			'class' => true,
			'compact' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'meta' => array
		(
			'content' => true,
			'dir' => true,
			'http-equiv' => true,
			'lang' => true,
			'name' => true,
			'scheme' => true
		),
		'noframes' => array
		(
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'noscript' => array
		(
/*			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
*/
		),
		'object' => array
		(
			'align' => true,
			'allownetworking' => true,
			'allowscriptaccess' => true,
			'archive' => true,
			'autostart' => true,
			'border' => true,
			'class' => true,
			'classid' => true,
			'codebase' => true,
			'codetype' => true,
			'data' => true,
			'declare' => true,
			'dir' => true,
			'enablecontextmenu'=> true,
			'height' => true,
			'hspace' => true,
			'id' => true,
			'invokeurls' => true,
			'lang' => true,
			'name' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'src' => true,
			'standby' => true,
			'style' => true,
			'tabindex' => true,
			'title' => true,
			'type' => true,
			'usemap' => true,
			'vspace' => true,
			'width' => true
		),
		'ol' => array
		(
			'class' => true,
			'compact' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'start' => true,
			'style' => true,
			'title' => true,
			'type' => true
		),
		'optgroup' => array
		(
			'class' => true,
			'dir' => true,
			'disabled' => true,
			'id' => true,
			'label' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'option' => array
		(
			'class' => true,
			'dir' => true,
			'disabled' => true,
			'id' => true,
			'label' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'selected' => true,
			'style' => true,
			'title' => true,
			'value' => true
		),
		'p' => array
		(
			'align' => true,
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'param' => array
		(
			'id' => true,
			'name' => true,
			'type' => true,
			'value' => true,
			'valuetype' => true
		),
		'pre' => array
		(
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true,
			'width' => true
		),
		'q' => array
		(
			'cite' => true,
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		's' => array
		(
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'samp' => array
		(
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'script' => array
		(
			'charset' => true,
			'defer' => true,
			'language' => true,
			'src' => true,
			'type' => true
		),
		'select' => array
		(
			'class' => true,
			'dir' => true,
			'disabled' => true,
			'id' => true,
			'lang' => true,
			'multiple' => true,
			'name' => true,
			'onblur' => false,
			'onchange' => false,
			'onclick' => false,
			'ondblclick' => false,
			'onfocus' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'size' => true,
			'style' => true,
			'tabindex' => true,
			'title' => true
		),
		'small' => array
		(
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'span' => array
		(
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'strike' => array
		(
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'strong' => array
		(
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'style' => array
		(
			'dir' => true,
			'lang' => true,
			'media' => true,
			'title' => true,
			'type' => true
		),
		'sub' => array
		(
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'sup' => array
		(
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'table' => array
		(
			'align' => true,
			'bgcolor' => true,
			'border' => true,
			'cellpadding' => true,
			'cellspacing' => true,
			'class' => true,
			'dir' => true,
			'frame' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'rules' => true,
			'style' => true,
			'summary' => true,
			'title' => true,
			'width' => true
		),
		'tbody' => array
		(
			'align' => true,
			'char' => true,
			'charoff' => true,
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true,
			'valign' => true
		),
		'td' => array
		(
			'abbr' => true,
			'align' => true,
			'axis' => true,
			'bgcolor' => true,
			'char' => true,
			'charoff' => true,
			'class' => true,
			'colspan' => true,
			'dir' => true,
			'headers' => true,
			'height' => true,
			'id' => true,
			'lang' => true,
			'nowrap' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'rowspan' => true,
			'scope' => true,
			'style' => true,
			'title' => true,
			'valign' => true,
			'width' => true
		),
		'textarea' => array
		(
			'accesskey' => true,
			'class' => true,
			'cols' => true,
			'dir' => true,
			'disabled' => true,
			'id' => true,
			'lang' => true,
			'name' => true,
			'onblur' => false,
			'onchange' => false,
			'onclick' => false,
			'ondblclick' => false,
			'onfocus' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'onselect' => false,
			'readonly' => true,
			'rows' => true,
			'style' => true,
			'tabindex' => true,
			'title' => true
		),
		'tfoot' => array
		(
			'align' => true,
			'char' => true,
			'charoff' => true,
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true,
			'valign' => true
		),
		'th' => array
		(
			'abbr' => true,
			'align' => true,
			'axis' => true,
			'bgcolor' => true,
			'char' => true,
			'charoff' => true,
			'class' => true,
			'colspan' => true,
			'dir' => true,
			'headers' => true,
			'height' => true,
			'id' => true,
			'lang' => true,
			'nowrap' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'rowspan' => true,
			'scope' => true,
			'style' => true,
			'title' => true,
			'valign' => true,
			'width' => true
		),
		'thead' => array
		(
			'align' => true,
			'char' => true,
			'charoff' => true,
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true,
			'valign' => true
		),
		'title' => array
		(
			'dir' => true,
			'lang' => true
		),
		'tr' => array
		(
			'align' => true,
			'bgcolor' => true,
			'char' => true,
			'charoff' => true,
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true,
			'valign' => true
		),
		'tt' => array
		(
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'u' => array
		(
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		),
		'ul' => array
		(
			'class' => true,
			'compact' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true,
			'type' => true
		),
		'var' => array
		(
			'class' => true,
			'dir' => true,
			'id' => true,
			'lang' => true,
			'onclick' => false,
			'ondblclick' => false,
			'onkeydown' => false,
			'onkeypress' => false,
			'onkeyup' => false,
			'onmousedown' => false,
			'onmousemove' => false,
			'onmouseout' => false,
			'onmouseover' => false,
			'onmouseup' => false,
			'style' => true,
			'title' => true
		)
	);

	var $unanalyzed_tags = array
	(
		'textarea',
		'script',
		'style'
	);

	var $empty_tags = array
	(
		'!doctype',
		'area',
		'base',
		'basefont',
		'br',
		'hr',
		'img',
		'input',
		'link',
		'meta',
		'param'
	);

	var $empty_attributes = array
	(
		'checked',
		'compact',
		'declare',
		'defer',
		'disabled',
		'ismap',
		'multiple',
		'noresize',
		'nosave',
		'noshade',
		'nowrap',
		'readonly',
		'selected'
	);

	var $css_properties = array
	(
		// Text and Fonts:
		'font' => true,
		'font-family' => true,
		'font-size' => true,
		'font-weight' => true,
		'font-style' => true,
		'font-variant' => true,
		'line-height' => true,
		'letter-spacing' => true,
		'word-spacing' => true,
		'text-align' => true,
		'text-decoration' => true,
		'text-indent' => true,
		'text-transform' => true,
		'vertical-align' => true,
		'white-space' => true,

		// Colours and Backgrounds:
		'color' => true,
		'background-color' => true,
		'background' => true,
		'background-image' => true,
		'background-repeat' => true,
		'background-position' => true,
		'background-attachment' => true,

		// The Box Model - dimensions, padding, margin and borders:
		'padding' => true,
		'padding-top' => true,
		'padding-right' => true,
		'padding-bottom' => true,
		'padding-left' => true,
		'border' => true,
		'border-top' => true,
		'border-right' => true,
		'border-bottom' => true,
		'border-left' => true,
		'border-style' => true,
		'border-top-style' => true,
		'border-right-style' => true,
		'border-bottom-style' => true,
		'border-left-style' => true,
		'border-color' => true,
		'border-top-color' => true,
		'border-right-color' => true,
		'border-bottom-color' => true,
		'border-left-color' => true,
		'border-width' => true,
		'border-top-width' => true,
		'border-right-width' => true,
		'border-bottom-width' => true,
		'border-left-width' => true,
		'outline' => true,
		'outline-style' => true,
		'outline-color' => true,
		'outline-width' => true,
		'margin' => true,
		'margin-top' => true,
		'margin-right' => true,
		'margin-bottom' => true,
		'margin-left' => true,
		'width' => true,
		'height' => true,
		'min-width' => true,
		'max-width' => true,
		'min-height' => true,
		'max-height' => true,

		// Positioning and Display:
		'position' => true,
		'top' => true,
		'right' => true,
		'bottom' => true,
		'left' => true,
		'clip' => true,
		'overflow' => true,
		'z-index' => true,
		'float' => true,
		'clear' => true,
		'display' => true,
		'visibility' => true,

		// Lists:
		'list-style' => true,
		'list-style-type' => true,
		'list-style-image' => true,
		'list-style-position' => true,

		// Tables:
		'table-layout' => true,
		'border-collapse' => true,
		'border-spacing' => true,
		'empty-cells' => true,
		'caption-side' => true,

		// The Whole Shebang:
		'background' => true,
		'background-attachment' => true,
		'background-color' => true,
		'background-image' => true,
		'background-position' => true,
		'background-repeat' => true,
		'border' => true,
		'border-collapse' => true,
		'border-color' => true,
		'border-spacing' => true,
		'border-style' => true,
		'border-width' => true,
		'bottom' => true,
		'caption-side' => true,
		'clear' => true,
		'clip' => true,
		'color' => true,
		'content' => true,
		'counter-increment' => true,
		'counter-reset' => true,
		'cursor' => true,
		'direction' => true,
		'display' => true,
		'empty-cells' => true,
		'float' => true,
		'font' => true,
		'font-family' => true,
		'font-size' => true,
		'font-style' => true,
		'font-variant' => true,
		'font-weight' => true,
		'height' => true,
		'left' => true,
		'letter-spacing' => true,
		'line-height' => true,
		'list-style' => true,
		'list-style-image' => true,
		'list-style-position' => true,
		'list-style-type' => true,
		'margin' => true,
		'max-height' => true,
		'max-width' => true,
		'min-height' => true,
		'min-width' => true,
		'orphans' => true,
		'outline' => true,
		'outline-color' => true,
		'outline-style' => true,
		'outline-width' => true,
		'overflow' => true,
		'padding' => true,
		'page-break-after' => true,
		'page-break-before' => true,
		'page-break-inside' => true,
		'position' => true,
		'quotes' => true,
		'right' => true,
		'table-layout' => true,
		'text-align' => true,
		'text-decoration' => true,
		'text-indent' => true,
		'text-transform' => true,
		'top' => true,
		'unicode-bidi' => true,
		'vertical-align' => true,
		'visibility' => true,
		'white-space' => true,
		'widows' => true,
		'width' => true,
		'word-spacing' => true,
		'z-index' => true,

		// Generated Content:
		'content' => true,
		'counter-increment' => true,
		'counter-reset' => true,
		'quotes' => true,

		// Paged Media:
		'page-break-before' => true,
		'page-break-after' => true,
		'page-break-inside' => true,
		'orphans' => true,
		'widows' => true,

		// Misc.:
		'cursor' => true,
		'direction' => true,
		'unicode-bidi' => true
	);
}

?>